/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application.views;

import application.utils.DatabaseUtil;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author yusuf
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuView
     */
    public MenuView() {
        initComponents();
        sliderMenuDefault();
        Pane.add(Home);
        Pane.repaint();
        Pane.revalidate();
    }
    
    private void sliderMenuDefault(){
        slideMenuLaporan.setVisible(false);
    }
    
    private void showSubMenu(JPanel subMenu){
        if(subMenu.isVisible() == false){
            subMenu.setVisible(true);
        }else{
            subMenu.setVisible(false);
        }
    }
    
    public void start(){
        JFrame frame = new MenuView();
        frame.setTitle("Menu Frame");
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                JFrame frame = (JFrame)e.getSource();

                int result = JOptionPane.showConfirmDialog(
                    frame,
                    "Are you sure you want to exit the application?",
                    "Exit Application",
                    JOptionPane.YES_NO_OPTION);

                if (result == JOptionPane.YES_OPTION){
                    DatabaseUtil.getInstance().closeConnection();
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    System.exit(0);
                }
            }
        });
        // TODO add your custom frame code here:
        
       
        frame.setVisible( true );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        candidate = new javax.swing.JLabel();
        kriteria = new javax.swing.JLabel();
        slideMenuLaporan = new javax.swing.JPanel();
        laporanCalonPelamar = new javax.swing.JLabel();
        laporanPrioritasKriteria = new javax.swing.JLabel();
        laporanHasilSeleksi = new javax.swing.JLabel();
        laporan = new javax.swing.JLabel();
        seleksi = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        Pane = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();

        Home.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selamat Datang, di Aplikasi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistem Pendukung Keputusan Penerimaan Karyawan Paruh Waktu (Part-Time)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Menggunakan Metode AHP");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(551, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        Menu.setBackground(new java.awt.Color(0, 51, 102));
        Menu.setMaximumSize(new java.awt.Dimension(32767, 600));

        candidate.setBackground(new java.awt.Color(0, 51, 102));
        candidate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        candidate.setForeground(new java.awt.Color(255, 255, 255));
        candidate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        candidate.setText("       Data Calon Pelamar   ");
        candidate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        candidate.setOpaque(true);
        candidate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                candidateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                candidateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                candidateMouseExited(evt);
            }
        });

        kriteria.setBackground(new java.awt.Color(0, 51, 102));
        kriteria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kriteria.setForeground(new java.awt.Color(255, 255, 255));
        kriteria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kriteria.setText("Data Kriteria");
        kriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        kriteria.setOpaque(true);
        kriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kriteriaMouseExited(evt);
            }
        });

        slideMenuLaporan.setBackground(new java.awt.Color(80, 80, 80));
        slideMenuLaporan.setForeground(new java.awt.Color(255, 255, 255));

        laporanCalonPelamar.setBackground(new java.awt.Color(80, 80, 80));
        laporanCalonPelamar.setForeground(new java.awt.Color(255, 255, 255));
        laporanCalonPelamar.setText("    Laporan Calon Pelamar");
        laporanCalonPelamar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laporanCalonPelamar.setOpaque(true);
        laporanCalonPelamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanCalonPelamarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanCalonPelamarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanCalonPelamarMouseExited(evt);
            }
        });

        laporanPrioritasKriteria.setBackground(new java.awt.Color(80, 80, 80));
        laporanPrioritasKriteria.setForeground(new java.awt.Color(255, 255, 255));
        laporanPrioritasKriteria.setText("    Laporan Prioritas Kriteria");
        laporanPrioritasKriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laporanPrioritasKriteria.setOpaque(true);
        laporanPrioritasKriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanPrioritasKriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanPrioritasKriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanPrioritasKriteriaMouseExited(evt);
            }
        });

        laporanHasilSeleksi.setBackground(new java.awt.Color(80, 80, 80));
        laporanHasilSeleksi.setForeground(new java.awt.Color(255, 255, 255));
        laporanHasilSeleksi.setText("    Laporan Hasil Seleksi");
        laporanHasilSeleksi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laporanHasilSeleksi.setOpaque(true);
        laporanHasilSeleksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanHasilSeleksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanHasilSeleksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanHasilSeleksiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout slideMenuLaporanLayout = new javax.swing.GroupLayout(slideMenuLaporan);
        slideMenuLaporan.setLayout(slideMenuLaporanLayout);
        slideMenuLaporanLayout.setHorizontalGroup(
            slideMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(laporanCalonPelamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporanPrioritasKriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporanHasilSeleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slideMenuLaporanLayout.setVerticalGroup(
            slideMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slideMenuLaporanLayout.createSequentialGroup()
                .addComponent(laporanCalonPelamar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporanPrioritasKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporanHasilSeleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        laporan.setBackground(new java.awt.Color(0, 51, 102));
        laporan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        laporan.setForeground(new java.awt.Color(255, 255, 255));
        laporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laporan.setText("  Cetak Laporan");
        laporan.setOpaque(true);
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanMouseExited(evt);
            }
        });

        seleksi.setBackground(new java.awt.Color(0, 51, 102));
        seleksi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        seleksi.setForeground(new java.awt.Color(255, 255, 255));
        seleksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleksi.setText("Seleksi");
        seleksi.setOpaque(true);
        seleksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seleksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seleksiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(candidate, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
            .addComponent(kriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(seleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(slideMenuLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(candidate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slideMenuLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        judul1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        judul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/mytens-lite.png"))); // NOI18N
        judul1.setText("   Sistem Pendukung Keputusan Penerimaan Karyawan Metode AHP");
        judul1.setOpaque(true);

        Pane.setBackground(new java.awt.Color(255, 255, 255));
        Pane.setMaximumSize(new java.awt.Dimension(1200, 650));
        Pane.setMinimumSize(new java.awt.Dimension(380, 200));
        Pane.setPreferredSize(new java.awt.Dimension(600, 570));
        Pane.setLayout(new java.awt.CardLayout());

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("  Log Out");
        logout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logout.setOpaque(true);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void candidateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_candidateMouseClicked
        // TODO add your handling code here:
        // remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        // add Panel, add panel
        Pane.add(new MasterCandidate());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_candidateMouseClicked

    private void candidateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_candidateMouseEntered
        // TODO add your handling code here:
        candidate.setBackground(new Color(51,51,51));
        candidate.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_candidateMouseEntered

    private void candidateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_candidateMouseExited
        // TODO add your handling code here:
        candidate.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_candidateMouseExited

    private void kriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kriteriaMouseClicked
        // TODO add your handling code here:
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        // add Panel, add panel
        Pane.add(new CriteriaData());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_kriteriaMouseClicked

    private void kriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kriteriaMouseEntered
        // TODO add your handling code here:
        kriteria.setBackground(new Color(51,51,51));
        kriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_kriteriaMouseEntered

    private void kriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kriteriaMouseExited
        // TODO add your handling code here:
        kriteria.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_kriteriaMouseExited

    private void laporanCalonPelamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanCalonPelamarMouseClicked
        // TODO add your handling code here:
        try{
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_laporanCalonPelamarMouseClicked

    private void laporanCalonPelamarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanCalonPelamarMouseEntered
        // TODO add your handling code here:
        laporanCalonPelamar.setBackground(new Color(51,51,51));
        laporanCalonPelamar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanCalonPelamarMouseEntered

    private void laporanCalonPelamarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanCalonPelamarMouseExited
        // TODO add your handling code here:
        laporanCalonPelamar.setBackground(new Color(80,80,80));
    }//GEN-LAST:event_laporanCalonPelamarMouseExited

    private void laporanPrioritasKriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPrioritasKriteriaMouseClicked
        // TODO add your handling code here:
        try{
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_laporanPrioritasKriteriaMouseClicked

    private void laporanPrioritasKriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPrioritasKriteriaMouseEntered
        // TODO add your handling code here:
        laporanPrioritasKriteria.setBackground(new Color(51,51,51));
        laporanPrioritasKriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanPrioritasKriteriaMouseEntered

    private void laporanPrioritasKriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPrioritasKriteriaMouseExited
        // TODO add your handling code here:
        laporanPrioritasKriteria.setBackground(new Color(80,80,80));
    }//GEN-LAST:event_laporanPrioritasKriteriaMouseExited

    private void laporanHasilSeleksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanHasilSeleksiMouseClicked
        // TODO add your handling code here:
        try{
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_laporanHasilSeleksiMouseClicked

    private void laporanHasilSeleksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanHasilSeleksiMouseEntered
        // TODO add your handling code here:
        laporanHasilSeleksi.setBackground(new Color(51,51,51));
        laporanHasilSeleksi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanHasilSeleksiMouseEntered

    private void laporanHasilSeleksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanHasilSeleksiMouseExited
        // TODO add your handling code here:
        laporanHasilSeleksi.setBackground(new Color(80,80,80));
    }//GEN-LAST:event_laporanHasilSeleksiMouseExited

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        // TODO add your handling code here:
        showSubMenu(slideMenuLaporan);
    }//GEN-LAST:event_laporanMouseClicked

    private void laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseEntered
        // TODO add your handling code here:
        laporan.setBackground(new Color(51,51,51));
        laporan.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanMouseEntered

    private void laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseExited
        // TODO add your handling code here:
        laporan.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_laporanMouseExited

    private void seleksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleksiMouseClicked
        // TODO add your handling code here:
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        //add Panel, add panel
        Pane.add(new SelectionData());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_seleksiMouseClicked

    private void seleksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleksiMouseEntered
        // TODO add your handling code here:
        seleksi.setBackground(new Color(51,51,51));
        seleksi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_seleksiMouseEntered

    private void seleksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleksiMouseExited
        // TODO add your handling code here:
        seleksi.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_seleksiMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new LoginView().start();
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setBackground(new Color(51,51,51));
        logout.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setBackground(Color.BLACK);
    }//GEN-LAST:event_logoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Pane;
    private javax.swing.JLabel candidate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel kriteria;
    private javax.swing.JLabel laporan;
    private javax.swing.JLabel laporanCalonPelamar;
    private javax.swing.JLabel laporanHasilSeleksi;
    private javax.swing.JLabel laporanPrioritasKriteria;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel seleksi;
    private javax.swing.JPanel slideMenuLaporan;
    // End of variables declaration//GEN-END:variables
}
